engineStrict: true
packages:
  - "apps/*"
  - "packages/*"
minimumReleaseAge: 1440
preferWorkspacePackages: true
savePrefix: ""
catalog:
  "@mimorisuzuko/yuuka": "1.0.7"
  "@types/node": "24.12.2"
  "@types/react": "19.2.14"
  "@types/react-dom": "19.2.3"
  next: "16.2.4"
  react: "19.2.5"
  react-dom: "19.2.5"
  typescript: "6.0.3"
  zod: 4.3.6
trustPolicy: no-downgrade
overrides:
  semver: "^7.7.4"
