packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  sharp: true
catalog:
  "@mimorisuzuko/yuuka": "1.0.7"
  "@types/node": "24.12.2"
  "@types/react": "19.2.14"
  "@types/react-dom": "19.2.3"
  next: "16.2.4"
  react: "19.2.5"
  react-dom: "19.2.5"
  typescript: "6.0.3"
  zod: 4.4.1
engineStrict: true
overrides:
  semver: "^7.7.4"
preferWorkspacePackages: true
savePrefix: ""
trustPolicy: no-downgrade
