name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          cache: "pnpm"
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm eslint
      - name: Format
        run: pnpm biome
      - name: Type Check
        run: pnpm tsc
